version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: petitio
    versions:
    - 1.2.1
    - 1.3.0
  - dependency-name: typescript
    versions:
    - 4.2.3
