name: paste.gg
install: true
packagePath: .
commitMessageTemplate: "chore(paste.gg): release v{{new-version}}"
tagTemplate: v{{new-version}}
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: SerenModz21/paste.gg
gitHostVariant: github
