name: Beta

on:
  push:
    branches:
      - main

jobs:
  beta:
    name: Publish Beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore CI Cache
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-20-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Code
        run: yarn build
      - name: Push new code
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo -e "\n# Initialize some useful variables"
          REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          BRANCH_OR_TAG=`awk -F/ '{print $2}' <<< $GITHUB_REF`
          CURRENT_BRANCH=`awk -F/ '{print $NF}' <<< $GITHUB_REF`
          if [ "$BRANCH_OR_TAG" == "heads" ]; then
            SOURCE_TYPE="branch"
          else
            SOURCE_TYPE="tag"
          fi
          echo -e "\n# Checkout the repo in the target branch"
          TARGET_BRANCH="beta"
          git clone $REPO out -b $TARGET_BRANCH
          echo -e "\n# Remove any old files in the dist folder"
          rm -rfv out/dist/*
          echo -e "\n# Move the generated docs to the newly-checked-out repo, to be committed and pushed"
          rsync -vaI package.json out/
          rsync -vaI README.md out/
          rsync -vaI LICENSE out/
          rsync -vaI dist/ out/dist
          echo -e "\n# Commit and push"
          cd out
          git add --all .
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_EMAIL}"
          git commit -m "build: beta release for commit ${GITHUB_SHA}" || true
          git push origin $TARGET_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: github-actions[bot]
          GITHUB_EMAIL: github-actions[bot]@users.noreply.github.com
