name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: The number of the PR that is being deployed
        required: false
        type: string
      ref:
        description: The branch that is being deployed
        required: false
        default: main
        type: string
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Next to NPM
    runs-on: ubuntu-latest
    if: github.repository_owner == 'SerenModz21'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Packages
        run: yarn build

      - name: Bump Version
        id: bump
        run: |
          # Resolve the tag to be used. "next" for push events, "pr-{prNumber}" for dispatch events.
          TAG=$([[ ${{ github.event_name }} == 'push' ]] && echo 'next' || echo 'pr-${{ github.event.inputs.prNumber }}')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

          yarn bump --preid "${TAG}.$(git rev-parse --verify --short HEAD)" --skip-changelog

      - name: Publish to NPM
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.yarnpkg.com"
          yarn npm publish --tag "${{ steps.bump.outputs.tag }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://npm.pkg.github.com"
          yarn npm publish --tag "${{ steps.bump.outputs.tag }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
