name: Format

on: [push, pull_request]

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Format Code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: "--write **/*"
          commit_message: "🎨 Format the code"
          same_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
