name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: rm -rf node_modules/ && yarn

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@${GITHUB_ACTOR}"
      - name: Set up NPM authentication
        run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
      - run: rm -rf node_modules/ && yarn
      - run: git config --global user.email "${GITHUB_EMAIL}"
      - run: git config --global user.name "${GITHUB_ACTOR}"
      - run: npm publish
        env:
          GITHUB_ACTOR: SerenModz21
          GITHUB_EMAIL: ${{secrets.EMAIL}}
          NODE_AUTH_TOKEN: ${{secrets.GIT_PKG_TOKEN}}
